/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_cypdashuhn_reglynx_JNI */

#ifndef _Included_dev_cypdashuhn_reglynx_JNI
#define _Included_dev_cypdashuhn_reglynx_JNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     dev_cypdashuhn_reglynx_JNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dev_cypdashuhn_reglynx_JNI_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
